#cloud-config

users:
  - name: {{ .Values.Username }} 
    homedir: /home/{{ .Values.Username }}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
write_files:
  - path: /home/{{ .Values.Username }}/docker-compose.yaml
    content: |
{{ .Files.DockerCompose | indent 6 }}
  - path: /home/{{ .Values.Username }}/nginx.conf
    content: |
{{ .Files.NginxConf | indent 6 }}
runcmd:
  - echo "deb http://packages.cloud.google.com/apt gcsfuse-$(lsb_release -c -s) main" | tee /etc/apt/sources.list.d/gcsfuse.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  - apt-get update && apt-get install -y gcsfuse
  - mkdir -p {{ .Values.Ingress.TLS.Path }}
  - gcsfuse -o ro {{ .Values.Ingress.TLS.Bucket }} {{ .Values.Ingress.TLS.Path }}
  - curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
  - curl -L 'https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64' -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker login --username={{ .Values.DockerUser }} --password={{ .Values.DockerPassword }}
  - docker-compose -f /home/{{ .Values.Username }}/docker-compose.yaml pull
  - runuser -l {{ .Values.Username }} -c 'sudo docker-compose -f /home/{{ .Values.Username }}/docker-compose.yaml up -d'
