version: '3'

services:
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/{{ .Values.Username }}/nginx.conf:/etc/nginx/nginx.conf:ro
      - {{ .Values.Ingress.TLS.Path }}:{{ .Values.Ingress.TLS.Path }}
  {{ .Values.Service.Name }}:
    image: "{{ .Values.Service.ImageRepo }}:{{ .Values.Service.ImageTag }}"
    ports:
      {{ range $i, $port := .Values.Service.Ports -}}
      - "{{ $port.Port }}:{{ $port.Port }}"
      {{ end }}