version: '3'

services:
  nginx:
    image: "linuxserver/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - {{ .VolRoot }}/nginx.conf:/config/nginx/site-confs/default
      - {{ .VolRoot }}/digitalocean.ini:/config/dns-conf/digitalocean.ini
    environment:
      - URL={{ .Domain }}
      - SUBDOMAINS={{ .SubDomain }}
      - VALIDATION=dns
      - PGID=1
      - PUID=1
      - TZ=America/New_York
      - DNSPLUGIN=digitalocean
      - ONLY_SUBDOMAINS=true
  {{ .Name }}:
    image: "{{ .Image }}"
    ports:
      {{ range $i, $port := .Ports -}}
      - "{{ $port.Number }}:{{ $port.Number }}"
      {{ end }}
